/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    CloudImage: typeof import('./src/components/CloudImage.vue')['default']
    Home_page: typeof import('./src/components/Home_page.vue')['default']
    ListComment: typeof import('./src/components/ListComment.vue')['default']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    Post: typeof import('./src/components/Post.vue')['default']
    PushFile: typeof import('./src/components/PushFile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/SearchFilter.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SingUp: typeof import('./src/components/SingUp.vue')['default']
    SlideShow: typeof import('./src/components/SlideShow.vue')['default']
    TestDownload: typeof import('./src/components/TestDownload.vue')['default']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    UpLoad: typeof import('./src/components/UpLoad.vue')['default']
  }
}
